name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  id-token: write # for OICD connect with Codecov

jobs:
  test:
    name: Test on Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11', 'pre', 'nightly']
        julia-arch:
          - x64
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            julia-arch: x86
            julia-version: 'min'
          - os: ubuntu-latest
            julia-arch: x86
            julia-version: 'lts'
          - os: ubuntu-latest
            julia-arch: x86
            julia-version: '1'
          - os: windows-latest
            julia-arch: x64
            julia-version: 'min'
          - os: windows-latest
            julia-arch: x64
            julia-version: 'lts'
          - os: windows-latest
            julia-arch: x64
            julia-version: '1'
          - os: macOS-latest
            julia-arch: aarch64
            julia-version: 'lts'
          - os: macOS-latest
            julia-arch: aarch64
            julia-version: '1'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1.2
      - uses: codecov/codecov-action@v5.4.3
        with:
          files: lcov.info
          use_oidc: true
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
          flag-name: run-${{ matrix.os }}-${{ matrix.julia-version }}-${{ matrix.julia-arch }}
          parallel: true

  finish:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
